import { SiteProvider } from './contexts/SiteContext'
import { UserProvider } from './contexts/UserContext'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Porto | The Portfolio Builder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <SiteProvider>
        <UserProvider>
          <body className={inter.className}>{children}</body>
        </UserProvider>
      </SiteProvider>

    </html>
  )
}
